//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MevzuatOrg.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Haberler
    {
        public int HaberId { get; set; }
        public string Baslik { get; set; }
        public string Icerik { get; set; }
        public System.DateTime Tarih { get; set; }
        public System.Guid UserId { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
}
